morseCode = {
    'A': '.-',
    'B': '-...',
    'C': '-.-.',
    'D': '-..',
    'E': '.',
    'F': '..-.',
    'G': '--.',
    'H': '....',
    'I': '..',
    'J': '.---',
    'K': '-.-',
    'L': '.-..',
    'M': '--',
    'N': '-.',
    'O': '---',
    'P': '.--.',
    'Q': '--.-',
    'R': '.-.',
    'S': '...',
    'T': '-',
    'U': '..-',
    'V': '...-',
    'W': '.--',
    'X': '-..-',
    'Y': '-.--',
    'Z': '--..',
    '0': '-----',
    '1': '.----',
    '2': '..---',
    '3': '...--',
    '4': '....-',
    '5': '.....',
    '6': '-....',
    '7': '--...',
    '8': '---..',
    '9': '----.',
    ' ': '/',
    '.': '.-.-.-',
    ',': '--..--',
    '?': '..--..',
    '!': '-.-.--',
}

words = {
    'HELLO', 'WORLD', 'PYTHON', 'MORSE', 'CODE', 'LEARN', 'PROGRAMMING',
    'ALGORITHM', 'DATA', 'STRUCTURE', 'FUNCTION', 'VARIABLE', 'CLASS',
    'OBJECT', 'METHOD', 'LIBRARY', 'MODULE', 'PACKAGE', 'SCRIPT', 'DEBUG',
    'TEST', 'EXCEPTION', 'IMPORT', 'EXPORT', 'ENCODE', 'DECODE', 'STRING',
    'INTEGER', 'FLOAT', 'BOOLEAN', 'LIST', 'TUPLE', 'SET', 'DICTIONARY',
    'ARRAY', 'LOOP', 'CONDITION', 'IF', 'ELSE', 'ELIF', 'FOR', 'WHILE',
    'SWITCH', 'CASE', 'BREAK', 'CONTINUE', 'RETURN', 'YIELD', 'ASSERT',
    'TRY', 'EXCEPT', 'FINALLY', 'RAISE', 'WITH', 'AS', 'IMPORTS', 'EXPORTS',
    'ENCODING', 'DECODING', 'STRINGIFY', 'PARSE', 'COMPILE', 'EXECUTE',
}

sentences = (
    'HELLO WORLD', 'PYTHON IS FUN', 'LEARN MORSE CODE', 'PROGRAMMING IS GREAT',
    'DATA STRUCTURES ARE IMPORTANT', 'FUNCTIONS AND METHODS', 'OBJECT ORIENTED PROGRAMMING',
    'ALGORITHMS AND COMPLEXITY', 'DEBUGGING AND TESTING', 'EXCEPTIONS AND ERROR HANDLING',
    'IMPORTING MODULES', 'EXPORTING DATA', 'ENCODING, DECODING STRINGS',
    'LISTS AND DICTIONARIES IN PYTHON', 'LOOPS AND CONDITIONS IN PROGRAMMING'
    'S.O.S', 'DO YOU LIKE PYTHON?', 'MORSE CODE IS COOL!',
)